name: ltfest
description: "LT Fest"
publish_to: 'none'
version: 0.2.2+27

uses-material-design: true

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.0.8
  flutter_typeahead: ^5.2.0
  go_router: ^14.8.1
  http: ^1.2.2
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  synchronized: ^3.3.1
  pinput: ^5.0.1
  mask_text_input_formatter: ^2.9.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0
  story_view: ^0.16.6
  dio_smart_retry: ^7.0.1
  carousel_slider: ^5.1.1
  share_plus: ^11.1.0
  collection: ^1.19.1
  flutter_custom_tabs: ^2.4.0
  app_links: ^6.4.1
  sentry_flutter: ^9.7.0
  sentry_dio: ^9.12.0
  flutter_native_splash: ^2.4.7
  connectivity_plus: ^7.0.0
  cached_network_image: ^3.4.1
  dio_cache_interceptor: ^4.0.5
  http_cache_hive_store: ^5.0.1
  image_picker: ^1.2.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.0.0
  huawei_push: ^6.14.0+300
  google_api_availability: ^5.0.1

dev_dependencies:
  sentry_dart_plugin: ^3.1.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15
  custom_lint:
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.4.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/social/
    - assets/icons/states/
    - assets/icons/bottom_bar/
    - assets/icons/bottom_bar/blog/
    - assets/icons/bottom_bar/home/
    - assets/icons/bottom_bar/lab/
    - assets/icons/bottom_bar/lt/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700

    - family: Unbounded
      fonts:
        - asset: assets/fonts/Unbounded-SemiBold.ttf
          weight: 600

sentry:
  upload_debug_symbols: true
  upload_source_maps: true
  project: flutter
  org: ltfest

flutter_native_splash:
  fullscreen: false
  color: "#BAD712"

  android_12:
    color: "#BAD712"
    image: assets/images/splash_icon.png
